name: Deploy

on: deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'pending'
          token: '${{ github.token }}'
      - uses: blaadje/github-package-version-bumper@master
        with:
          github-token: ${{ secrets.github_token }}

  deploy:
    needs: [build]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.16.2]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Fetch commits
        shell: bash
        run: |
          if [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]];
          then git pull;
          else  
          git fetch;
          git checkout origin/master -- package.json;
          fi;

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.2.0
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: true

      - uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: alexandrecharlot
          SENTRY_PROJECT: todolist
        with:
          tagName: ${{ github.ref }}
          environment: production
          sourceMapOptions: '{"include": ["dist"]}'

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'success'
          token: '${{ github.token }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'failure'
          token: '${{ github.token }}'
