name: Deploy for preview

on: 
  pull_request:
    branches: [master]

jobs:
  preview:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.2.0
        with:
          github_token: ${{ secrets.github_token }}

      - name: Deploy S3 Website
        uses: blaadje/s3-website-pr-action@directLinkToDownload
        with:
          bucket-prefix: "blaadje-todo-list-app"
          folder-to-copy: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
